## Model Training

In [113]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline
# Modelling
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

In [114]:
df = pd.read_csv('data/stud.csv')
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [115]:
X = df.drop(['math_score'],axis=1)
y = df['math_score']

In [116]:
X

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75
...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,99,95
996,male,group C,high school,free/reduced,none,55,55
997,female,group C,high school,free/reduced,completed,71,65
998,female,group D,some college,standard,completed,78,77
999,female,group D,some college,free/reduced,none,86,86

In [117]:
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [118]:
num_features = X.select_dtypes(exclude='object').columns
cat_features = X.select_dtypes(include='object').columns

print('Numeric Features: ', num_features)
print('Categorical Features: ', cat_features)

Numeric Features:  Index(['reading_score', 'writing_score'], dtype='object')
Categorical Features:  Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='object')

In [119]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [120]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
num_transformer = StandardScaler()
cat_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ('StandardScaler', num_transformer, num_features),
        ('OneHotEncoder', cat_transformer, cat_features)
    ]
)

In [121]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [122]:
def eval_model(true, pred):
    mae = mean_absolute_error(true, pred)
    mse = mean_squared_error(true, pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(true, pred)
    adj_r2 = 1 - (1-r2)*(len(true)-1)/(len(true)-X.shape[1]-1)
    return mae, mse, rmse, r2, adj_r2

In [123]:
models = {
    'Linear Regression': LinearRegression(),
    'Ridge': Ridge(),
    'Lasso': Lasso(),
    'KNN': KNeighborsRegressor(),
    'Decision Tree': DecisionTreeRegressor(),
    'Random Forest': RandomForestRegressor(),
    'AdaBoost': AdaBoostRegressor(),
    'SVM': SVR(),
    'CatBoost': CatBoostRegressor(verbose=0),
    'XGBoost': XGBRegressor()
}

results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    train_mae, train_mse, train_rmse, train_r2, train_adj_r2 = eval_model(y_train, y_train_pred)
    test_mae, test_mse, test_rmse, test_r2, test_adj_r2 = eval_model(y_test, y_test_pred)

    results.append({
        'Model': name,
        'accuracy': test_r2,
    })

    print(f'=============================================== {name} ===========================================')
    print('\nModel Performance for Trainning Set')
    print('Mean Absolute Error:', train_mae)
    print('Mean Squared Error:', train_mse)
    print('Root Mean Squared Error:', train_rmse)
    print('R2 Score:', train_r2)
    print('Adjusted R2 Score:', train_adj_r2)
    print('---------------------------------------------------------------------------------------------------')
    print('\nModel Performance for Test Set')
    print('Mean Absolute Error:', test_mae)
    print('Mean Squared Error:', test_mse)
    print('Root Mean Squared Error:', test_rmse)
    print('R2 Score:', test_r2)
    print('Adjusted R2 Score:', test_adj_r2)
    print('====================================================================================================')
    print('\n')

=============================================== Linear Regression ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 4.266711846071957
Mean Squared Error: 28.33487038064859
Root Mean Squared Error: 5.323050852720514
R2 Score: 0.8743172040139593
Adjusted R2 Score: 0.8732063712211534
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 4.214763142474852
Mean Squared Error: 29.0951698667155
Root Mean Squared Error: 5.393993869732844
R2 Score: 0.8804332983749564
Adjusted R2 Score: 0.8760740957115434
====================================================================================================


=============================================== Ridge ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 4.26500882127927
Mean Squared Error: 28.33963485875214
Root Mean Squared Error: 5.3234983665586055
R2 Score: 0.8742960705864397
Adjusted R2 Score: 0.8731850510082895
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 4.212526820759747
Mean Squared Error: 29.091086457465504
Root Mean Squared Error: 5.393615342000716
R2 Score: 0.8804500791594524
Adjusted R2 Score: 0.8760914882954741
====================================================================================================


=============================================== Lasso ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 5.205260274468427
Mean Squared Error: 43.46106018771196
Root Mean Squared Error: 6.592500298650881
R2 Score: 0.8072231322208645
Adjusted R2 Score: 0.8055192962682711
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 5.155701094273798
Mean Squared Error: 42.47556715227399
Root Mean Squared Error: 6.517328221922998
R2 Score: 0.8254465092551196
Adjusted R2 Score: 0.8190825799050458
====================================================================================================


=============================================== KNN ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 4.4595
Mean Squared Error: 31.046400000000002
Root Mean Squared Error: 5.571929647797072
R2 Score: 0.8622898815176547
Adjusted R2 Score: 0.8610727466320784
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 5.705
Mean Squared Error: 54.2006
Root Mean Squared Error: 7.362105677046479
R2 Score: 0.7772624460422194
Adjusted R2 Score: 0.7691418060541753
====================================================================================================


=============================================== Decision Tree ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 0.01875
Mean Squared Error: 0.078125
Root Mean Squared Error: 0.2795084971874737
R2 Score: 0.9996534669718089
Adjusted R2 Score: 0.999650404179893
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 6.2
Mean Squared Error: 60.14
Root Mean Squared Error: 7.754998388136518
R2 Score: 0.7528544611125905
Adjusted R2 Score: 0.743843946673987
====================================================================================================


=============================================== Random Forest ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 1.82008125
Mean Squared Error: 5.178307969635771
Root Mean Squared Error: 2.2755895872577225
R2 Score: 0.9770309793072106
Adjusted R2 Score: 0.9768279702859359
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 4.74381369047619
Mean Squared Error: 36.914642093750004
Root Mean Squared Error: 6.0757421023073395
R2 Score: 0.848299150098176
Adjusted R2 Score: 0.8427683899455054
====================================================================================================


=============================================== AdaBoost ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 4.6728943707369
Mean Squared Error: 32.74333579394677
Root Mean Squared Error: 5.722179287120142
R2 Score: 0.8547629144863292
Adjusted R2 Score: 0.8534792533769913
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 4.58943456471185
Mean Squared Error: 35.29242937830715
Root Mean Squared Error: 5.940743167172534
R2 Score: 0.8549656388868048
Adjusted R2 Score: 0.8496779278045529
====================================================================================================


=============================================== SVM ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 4.980786033005985
Mean Squared Error: 45.42934641565161
Root Mean Squared Error: 6.740129554812103
R2 Score: 0.7984925570283545
Adjusted R2 Score: 0.7967115569010799
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 5.499555048069601
Mean Squared Error: 69.70585108777921
Root Mean Squared Error: 8.349002999626913
R2 Score: 0.7135435628417907
Adjusted R2 Score: 0.7030998385703976
====================================================================================================


=============================================== CatBoost ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 2.4444683752477294
Mean Squared Error: 9.579512530108037
Root Mean Squared Error: 3.095078759920018
R2 Score: 0.9575088961836384
Adjusted R2 Score: 0.9571333434983929
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 4.631211143921056
Mean Squared Error: 36.43682237965824
Root Mean Squared Error: 6.036292105229687
R2 Score: 0.8502627518728724
Adjusted R2 Score: 0.8448035813682375
====================================================================================================


=============================================== XGBoost ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 0.7100880146026611
Mean Squared Error: 1.1044906377792358
Root Mean Squared Error: 1.0509474952533242
R2 Score: 0.9951009154319763
Adjusted R2 Score: 0.9950576154421075
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 5.131189346313477
Mean Squared Error: 43.576168060302734
Root Mean Squared Error: 6.601224739417886
R2 Score: 0.8209235668182373
Adjusted R2 Score: 0.8143947385251522
====================================================================================================

In [124]:
results = pd.DataFrame(results)
results

               Model  accuracy
0  Linear Regression  0.880433
1              Ridge  0.880450
2              Lasso  0.825447
3                KNN  0.777262
4      Decision Tree  0.752854
5      Random Forest  0.848299
6           AdaBoost  0.854966
7                SVM  0.713544
8           CatBoost  0.850263
9            XGBoost  0.820924

In [125]:
results = results.sort_values(by='accuracy', ascending=False)
results

               Model  accuracy
1              Ridge  0.880450
0  Linear Regression  0.880433
6           AdaBoost  0.854966
8           CatBoost  0.850263
5      Random Forest  0.848299
2              Lasso  0.825447
9            XGBoost  0.820924
3                KNN  0.777262
4      Decision Tree  0.752854
7                SVM  0.713544

In [126]:
results = results.head()
results

               Model  accuracy
1              Ridge  0.880450
0  Linear Regression  0.880433
6           AdaBoost  0.854966
8           CatBoost  0.850263
5      Random Forest  0.848299

# Hyperparameter Tuning

In [127]:
rf_params = {
    'criterion': ['squared_error', 'friedman_mse', 'poisson'],
    'max_depth': [None, 1, 5, 10, 15, 20],
    'min_samples_split': [2, 8, 15, 20],
    'n_estimators': [10, 50, 100, 200, 500],
    'max_features': [None, 'sqrt', 'log2']
}

ab_params = {
    'n_estimators': [10, 50, 100, 200, 500],
    'learning_rate': [0.1, 0.5, 1.0, 1.5, 2.0],
    'loss': ['linear', 'square', 'exponential'],
}

In [128]:
from sklearn.model_selection import GridSearchCV

grid_models = [
    ('Random Forest', RandomForestRegressor(), rf_params),
    ('AdaBoost', AdaBoostRegressor(), ab_params),
]

results = []
for name, model, params in grid_models:
    grid = GridSearchCV(estimator=model, param_grid=params, cv=3, scoring='accuracy', n_jobs=-1, verbose=2)
    grid.fit(X_train, y_train)

    y_train_pred = grid.predict(X_train)
    y_test_pred = grid.predict(X_test)

    train_mae, train_mse, train_rmse, train_r2, train_adj_r2 = eval_model(y_train, y_train_pred)
    test_mae, test_mse, test_rmse, test_r2, test_adj_r2 = eval_model(y_test, y_test_pred)

    results.append({
        'Model': model,
        'Params': grid.best_params_,
        'accuracy': test_r2,
    })

    print(f'=============================================== {name} ===========================================')
    print('\nModel Performance for Trainning Set')
    print('Mean Absolute Error:', train_mae)
    print('Mean Squared Error:', train_mse)
    print('Root Mean Squared Error:', train_rmse)
    print('R2 Score:', train_r2)
    print('Adjusted R2 Score:', train_adj_r2)
    print('---------------------------------------------------------------------------------------------------')
    print('\nModel Performance for Test Set')
    print('Mean Absolute Error:', test_mae)
    print('Mean Squared Error:', test_mse)
    print('Root Mean Squared Error:', test_rmse)
    print('R2 Score:', test_r2)
    print('Adjusted R2 Score:', test_adj_r2)
    print('====================================================================================================')
    print('\n')

Fitting 3 folds for each of 1080 candidates, totalling 3240 fits
=============================================== Random Forest ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 2.013125
Mean Squared Error: 7.332313194444445
Root Mean Squared Error: 2.707824439369075
R2 Score: 0.967476624705067
Adjusted R2 Score: 0.9671891706304906
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 4.77275
Mean Squared Error: 39.2619125
Root Mean Squared Error: 6.265932691946188
R2 Score: 0.8386530342107945
Adjusted R2 Score: 0.8327705927497298
====================================================================================================


Fitting 3 folds for each of 75 candidates, totalling 225 fits
=============================================== AdaBoost ===========================================

Model Performance for Trainning Set
Mean Absolute Error: 5.762213568994932
Mean Squared Error: 50.2657137199127
Root Mean Squared Error: 7.089831713088309
R2 Score: 0.7770402561337602
Adjusted R2 Score: 0.7750696523369626
---------------------------------------------------------------------------------------------------

Model Performance for Test Set
Mean Absolute Error: 5.605695944128627
Mean Squared Error: 54.37896766035337
Root Mean Squared Error: 7.374209629536806
R2 Score: 0.7765294435224634
Adjusted R2 Score: 0.7683820794842199
====================================================================================================

In [129]:
results = pd.DataFrame(results)
results.sort_values(by='accuracy', ascending=False)

,Model,Params,accuracy
0,RandomForestRegressor(),"{'criterion': 'squared_error', 'max_depth': No...",0.838653
1,AdaBoostRegressor(),"{'learning_rate': 0.1, 'loss': 'linear', 'n_es...",0.776529

In [130]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

num_features = X.select_dtypes(exclude='object').columns
cat_features = X.select_dtypes(include='object').columns

preprocessor = ColumnTransformer(
    [
        ('StandardScaler', StandardScaler(), num_features),
        ('OneHotEncoder', OneHotEncoder(), cat_features)
    ], remainder='passthrough'
)

In [131]:
from sklearn.pipeline import Pipeline

pipe = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('StandardScaler',
                                                  StandardScaler(),
                                                  Index(['reading_score', 'writing_score'], dtype='object')),
                                                 ('OneHotEncoder',
                                                  OneHotEncoder(),
                                                  Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='object'))])),
                ('model', LinearRegression())])